<?xml version = '1.0' encoding = 'utf-8'?>
<!--Generated by Oracle BI Publisher 10.1.3.4.1-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ora="http://www.oracle.com/XSL/Transform/java/" xmlns:xdofo="http://xmlns.oracle.com/oxp/fo/extensions" xmlns:xdoxslt="http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions" xmlns:xdoxliff="urn:oasis:names:tc:xliff:document:1.1" xmlns:xlink="http://www.w3.org/1999/xlink">
   <xsl:param name="_XDOCALENDAR">GREGORIAN</xsl:param>
   <xsl:param name="_XDOLOCALE">en-US</xsl:param>
   <xsl:param name="_XDOTIMEZONE">GMT</xsl:param>
   <xsl:param name="_XDODFOVERRIDE">;</xsl:param>
   <xsl:param name="_XDOCURMASKS">;</xsl:param>
   <xsl:param name="_XDONFSEPARATORS"></xsl:param>
   <xsl:param name="_XDOCHARTTYPE">image/svg+xml</xsl:param>
   <xsl:param name="_XDOOUTPUTFORMAT">application/pdf</xsl:param>
   <xsl:param name="_XDOSVGFONTEMBED">true</xsl:param>
   <xsl:param name="_XDOCTX">#</xsl:param>
   <xsl:variable name="_XDOXSLTCTX" select="xdoxslt:set_xslt_locale($_XDOCTX, $_XDOLOCALE, $_XDOTIMEZONE, $_XDOCALENDAR, concat($_XDODFOVERRIDE,'',$_XDOCURMASKS,'',$_XDONFSEPARATORS))"/>
   <xsl:variable name="_XDOFOPOS" select="''"/>
   <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
   <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
   <xsl:variable name="_XDOFOOSTOTAL" select="number(0)"/>
   <xsl:template match="/">
      <fo:root xdofo:nf-separator="{$_XDONFSEPARATORS}">
         <xdofo:list-styles>
            <xdofo:list-template template-id="-119">
               <xdofo:list-level format-code="23" header-align="before" char-follow="tab" start-at="1" header-text="" first-line-indent="-18.0pt" left-indent="18.0pt" before-indent="18.0pt" list-tab="18.0pt" font-family="Symbol"/>
            </xdofo:list-template>
            <xdofo:list-style style-id="16" template-id="-119"/>
            <xdofo:list-style style-id="15" template-id="-119"/>
            <xdofo:list-style style-id="14" template-id="-119"/>
            <xdofo:list-style style-id="13" template-id="-119"/>
            <xdofo:list-style style-id="12" template-id="-119"/>
            <xdofo:list-style style-id="11" template-id="-119"/>
            <xdofo:list-style style-id="10" template-id="-119"/>
            <xdofo:list-style style-id="9" template-id="-119"/>
            <xdofo:list-style style-id="8" template-id="-119"/>
            <xdofo:list-style style-id="7" template-id="-119"/>
            <xdofo:list-style style-id="6" template-id="-119"/>
            <xdofo:list-style style-id="5" template-id="-119"/>
            <xdofo:list-style style-id="4" template-id="-119"/>
            <xdofo:list-style style-id="3" template-id="-119"/>
            <xdofo:list-style style-id="2" template-id="-119"/>
            <xdofo:list-style style-id="1" template-id="-119"/>
         </xdofo:list-styles>
         <fo:layout-master-set>
            <fo:simple-page-master master-name="master0" margin-left="30.6pt" margin-right="30.6pt" page-height="792.0pt" page-width="612.0pt" margin-top="7.1pt" margin-bottom="14.45pt">
               <fo:region-before region-name="region-header" extent="10.75pt"/>
               <fo:region-body region-name="region-body" margin-top="10.75pt" margin-bottom="21.55pt"/>
               <fo:region-after region-name="region-footer" extent="21.55pt" display-align="after"/>
            </fo:simple-page-master>
         </fo:layout-master-set>
         <fo:page-sequence master-reference="master0">
            <fo:title>RTF Template</fo:title>
            <xsl:variable name="_PW" select="number(612.0)" xdofo:alt="internal"/>
            <xsl:variable name="_PH" select="number(792.0)" xdofo:alt="internal"/>
            <xsl:variable name="_ML" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MR" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_MT" select="number(17.85)" xdofo:alt="internal"/>
            <xsl:variable name="_MB" select="number(36.0)" xdofo:alt="internal"/>
            <xsl:variable name="_HY" select="number(7.1000004)" xdofo:alt="internal"/>
            <xsl:variable name="_FY" select="number(14.450001)" xdofo:alt="internal"/>
            <xsl:variable name="_SECTION_NAME" select="string('master0')" xdofo:alt="internal"/>
            <fo:static-content flow-name="region-header"/>
            <fo:static-content flow-name="region-footer">
               <fo:block xdofo:tab-stops="left:496.15pt:dots" text-align="start" orphans="2" start-indent="218.05pt" linefeed-treatment="preserve" padding-top="12.0pt" end-indent="5.4pt" padding-bottom="0.0pt" height="0.0pt" widows="2" text-indent="0.0pt">
                  <fo:leader font-size="15.0pt" font-family="Calibri" leader-pattern="space" leader-length="35.45pt"/>
                  <fo:inline xml:space="preserve" font-size="15.0pt" white-space-collapse="false" height="17.34pt" font-family="Calibri">Set: </fo:inline>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
               </fo:block>
               <fo:block xdofo:tab-stops="left:496.15pt:dots" text-align="start" orphans="2" start-indent="218.05pt" linefeed-treatment="preserve" padding-top="12.0pt" end-indent="5.4pt" padding-bottom="0.0pt" height="0.0pt" widows="2" text-indent="0.0pt">
                  <fo:leader font-size="15.0pt" font-family="Calibri" leader-pattern="space" leader-length="35.45pt"/>
                  <fo:inline xml:space="preserve" font-size="15.0pt" white-space-collapse="false" height="17.34pt" font-family="Calibri">Load: </fo:inline>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
               </fo:block>
               <fo:block xdofo:tab-stops="left:226.8pt:dots left:248.1pt:space left:496.15pt:dots" text-align="start" orphans="2" start-indent="5.4pt" linefeed-treatment="preserve" padding-top="12.0pt" end-indent="5.4pt" padding-bottom="0.0pt" height="0.0pt" widows="2">
                  <fo:inline xml:space="preserve" font-size="15.0pt" white-space-collapse="false" height="17.34pt" font-family="Calibri">Sorted: </fo:inline>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
                  <fo:inline xml:space="preserve" font-size="15.0pt" white-space-collapse="false" height="17.34pt" font-family="Calibri">Verified: </fo:inline>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
               </fo:block>
               <fo:block xdofo:tab-stops="left:226.8pt:dots left:248.1pt:space left:496.15pt:dots" text-align="start" orphans="2" start-indent="5.4pt" linefeed-treatment="preserve" padding-top="12.0pt" end-indent="5.4pt" padding-bottom="12.0pt" height="0.0pt" widows="2">
                  <fo:inline xml:space="preserve" font-size="15.0pt" white-space-collapse="false" height="17.34pt" font-family="Calibri">Date: </fo:inline>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
                  <fo:inline xml:space="preserve" font-size="15.0pt" white-space-collapse="false" height="17.34pt" font-family="Calibri">Teardown: </fo:inline>
                  <xdofo:tab font-size="15.0pt" font-family="Calibri"/>
               </fo:block>
            </fo:static-content>
            <fo:flow flow-name="region-body">
               <fo:block xdofo:tab-stops="right:496.15pt:dots" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt" start-indent="5.4pt"/>
               <xsl:variable name="_XDOFOOSTOTAL" select="(number(concat('0', $_XDOFOPOS2)) - 1) * number(concat('0', $_XDOFOTOTAL))"/>
               <xsl:for-each select=".//JOBS_ROW">
                  <xsl:variable name="_XDOFOPOS" select="concat($_XDOFOPOS, '_', position())"/>
                  <xsl:variable name="_XDOFOPOS2" select="number(concat('0', $_XDOFOOSTOTAL)) + position()"/>
                  <xsl:if test=".//L_JOBNAME!=''">
                     <fo:block xdofo:tab-stops="right:496.15pt:dots" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="0.0pt" end-indent="5.4pt" padding-top="0.0pt">
                        <fo:table start-indent="0.0pt" style-id="ts15" style-name="Table Grid" xdofo:table-summary="Template Table 1" xdofo:row-header-count="0">
                           <xsl:variable name="_XDOFOPOS2" select="number(1)"/>
                           <xsl:variable name="_XDOFOTOTAL" select="number(1)"/>
                           <fo:table-column column-width="261.4pt"/>
                           <fo:table-column column-width="285.1pt"/>
                           <fo:table-body>
                              <fo:table-row>
                                 <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="18.0pt" number-columns-spanned="1">
                                    <fo:block xdofo:tab-stops="right:496.15pt:dots" xdofo:xliff-note="L_SEQ_NUM" text-align="start" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="2.0pt" end-indent="0.0pt" padding-bottom="6.0pt" height="0.0pt" widows="2">
                                       <fo:inline height="12.0pt" font-size="12.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">
                                          <xsl:value-of select=".//L_SEQ_NUM" xdofo:field-name="L_SEQ_NUM"/>
                                       </fo:inline>
                                       <fo:inline height="10.0pt" font-size="10.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">.</fo:inline>
                                    </fo:block>
                                    <fo:block xdofo:xliff-note="L_JOBNAME" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0.0pt" widows="2">
                                       <fo:inline height="16.0pt" font-size="16.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">
                                          <xsl:value-of select=".//L_JOBNAME" xdofo:field-name="L_JOBNAME"/>
                                       </fo:inline>
                                    </fo:block>
                                    <fo:block xdofo:tab-stops="left:0.0pt:space left:22.5pt:space left:108.0pt:space left:288.0pt:space left:396.0pt:space" xdofo:xliff-note="L_JOBNAME" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0.0pt" widows="2">
                                       <fo:inline height="18.0pt" font-family="3 of 9 Barcode" white-space-collapse="false" font-size="18.0pt">*<xsl:value-of select=".//L_JOBNAME" xdofo:field-name="L_JOBNAME"/>*</fo:inline>
                                    </fo:block>
                                    <fo:block xdofo:xliff-note="L_PART_NUMBER" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0.0pt" widows="2">
                                       <fo:inline height="18.0pt" font-size="18.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">
                                          <xsl:value-of select=".//L_PART_NUMBER" xdofo:field-name="L_PART_NUMBER"/>
                                       </fo:inline>
                                    </fo:block>
                                    <fo:block xdofo:xliff-note="L_QUANTITY" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="6.0pt" height="0.0pt" widows="2">
                                       <fo:inline xml:space="preserve" height="15.0pt" font-size="15.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">Qty: <xsl:value-of select=".//L_QUANTITY" xdofo:field-name="L_QUANTITY"/></fo:inline>
                                    </fo:block>
                                 </fo:table-cell>
                                 <fo:table-cell padding-end="5.4pt" padding-bottom="0.0pt" padding-start="5.4pt" padding-top="0.0pt" vertical-align="middle" height="18.0pt" number-columns-spanned="1">
                                    <xsl:if test=".//R_JOBNAME!=''" xdofo:ctx="3">
                                       <fo:block xdofo:xliff-note="C, R_SEQ_NUM" text-align="start" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="3.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0pt" widows="2">
                                          <fo:inline height="12.0pt" font-size="12.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">
                                             <xsl:value-of select=".//R_SEQ_NUM" xdofo:field-name="R_SEQ_NUM"/>
                                          </fo:inline>
                                          <fo:inline height="10.0pt" font-size="10.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">.</fo:inline>
                                       </fo:block>
                                       <fo:block xdofo:xliff-note="R_JOBNAME" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0.0pt" widows="2">
                                          <fo:inline height="16.0pt" font-size="16.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">
                                             <xsl:value-of select=".//R_JOBNAME" xdofo:field-name="R_JOBNAME"/>
                                          </fo:inline>
                                       </fo:block>
                                       <fo:block xdofo:xliff-note="R_JOBNAME" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0.0pt" widows="2">
                                          <fo:inline height="18.0pt" font-family="3 of 9 Barcode" white-space-collapse="false" font-size="18.0pt">*<xsl:value-of select=".//R_JOBNAME" xdofo:field-name="R_JOBNAME"/>*</fo:inline>
                                       </fo:block>
                                       <fo:block xdofo:xliff-note="R_PART_NUMBER" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="3.0pt" height="0.0pt" widows="2">
                                          <fo:inline height="18.0pt" font-size="18.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">
                                             <xsl:value-of select=".//R_PART_NUMBER" xdofo:field-name="R_PART_NUMBER"/>
                                          </fo:inline>
                                       </fo:block>
                                       <fo:block xdofo:xliff-note="R_QUANTITY, EC" text-align="center" orphans="2" start-indent="0.0pt" linefeed-treatment="preserve" padding-top="0.0pt" end-indent="0.0pt" padding-bottom="6.0pt" height="0pt" widows="2">
                                          <fo:inline xml:space="preserve" height="15.0pt" font-size="15.0pt" font-weight="bold" color="#000000" font-family="Univers Com 55" white-space-collapse="false">Qty: <xsl:value-of select=".//R_QUANTITY" xdofo:field-name="R_QUANTITY"/></fo:inline>
                                       </fo:block>
                                    </xsl:if>
                                 </fo:table-cell>
                              </fo:table-row>
                           </fo:table-body>
                        </fo:table>
                     </fo:block>
                     <fo:block xdofo:tab-stops="left:496.15pt:dots" orphans="2" widows="2" linefeed-treatment="preserve" text-align="start" padding-bottom="6.0pt" end-indent="5.4pt" padding-top="2.0pt" start-indent="5.4pt"/>
                  </xsl:if>
               </xsl:for-each>
               <fo:block height="0pt">
                  <fo:inline id="{concat('page-total-', $_SECTION_NAME, $_XDOFOPOS)}"/>
                  <fo:inline id="{concat('page-total', $_XDOFOPOS)}"/>
               </fo:block>
            </fo:flow>
         </fo:page-sequence>
      </fo:root>
   </xsl:template>
</xsl:stylesheet>
